name: hello_flutter
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  pull_to_refresh: ^1.1.5
  cupertino_icons: ^0.1.2
  http: any
  flutter_spinkit: ^2.1.0 #一个多种样式loading的三方库
  cached_network_image: any #允许缓存图片的三方库 类似于SDWebImage
  flutter_cache_manager: any #这个傻逼pub竟然还有三方库互相依赖的版本冲突问题-，- 这很不google
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #字体资源文件配置
  fonts:
    - family: WechatIconFontFamily
      fonts:
        - asset: assets/fonts/iconfont.ttf
  
  #图片资源配置
  assets:
    - assets/images/ic_file_transfer.png
    - assets/images/ic_fengchao.png
    - assets/images/ic_tx_news.png
    - assets/images/ic_wx_games.png
    - assets/images/ic_new_friend.png
    - assets/images/ic_group_chat.png
    - assets/images/ic_tag.png
    - assets/images/ic_public_account.png
    - assets/images/ic_bottle_msg.png
    - assets/images/ic_feeds.png
    - assets/images/ic_game_entry.png
    - assets/images/ic_mini_program.png
    - assets/images/ic_people_nearby.png
    - assets/images/ic_quick_scan.png
    - assets/images/ic_quick_search.png
    - assets/images/ic_shake_phone.png
    - assets/images/ic_shopping.png
    - assets/images/ic_social_circle.png
    - assets/images/ic_wallet.png
    - assets/images/ic_album.png
    - assets/images/ic_collections.png
    - assets/images/ic_cards_wallet.png
    - assets/images/ic_emotions.png
    - assets/images/ic_settings.png
    - assets/images/ic_qrcode_preview_tiny.png
    - assets/images/default_nor_avatar.png
    - assets/images/user_avatar.png